import React, { useState } from 'react';
import ScoreRing from './ScoreRing.jsx';
import InterviewQuestions from './InterviewQuestions.jsx';
import RepoExplorer from './RepoExplorer.jsx';
import { Copy, Check, Printer, Share2, RefreshCw, CheckCircle2, AlertTriangle, Sparkles, Folder, Calendar } from 'lucide-react';

export default function ReportView({ reportData, onRefresh, isRefreshing }) {
  const [copiedMd, setCopiedMd] = useState(false);
  const [copiedBadge, setCopiedBadge] = useState(false);
  const [copiedLink, setCopiedLink] = useState(false);

  if (!reportData) return null;

  const { username, aiReport, rawAnalysis, cached, cachedAt, reportId } = reportData;
  const sp = rawAnalysis.standaloneProjects;
  const ar = rawAnalysis.assignmentRepos;
  const standaloneScore = sp.consistency ? sp.consistency.averageSignalScore : (sp.repoAnalyses.length ? sp.repoAnalyses[0].overallSignalScore : 70);
  const overallScore = standaloneScore || 70;

  const handleCopyMarkdown = () => {
    const text = `# GitHub Authenticity Report: @${username}\n\nGenerated by TrustScore AI\nOverall Authenticity Score: ${overallScore}/100\n\n## Standalone Summary\n${aiReport.standalone_summary || 'N/A'}\n\n## Positive Signals\n${(aiReport.positive_signals || []).map(s => `- ${s}`).join('\n')}\n\n## Review Flags\n${(aiReport.worth_reviewing || []).map(s => `- ${s}`).join('\n')}\n\n## Recommendation\n${aiReport.recommendation}\n`;
    navigator.clipboard.writeText(text).then(() => {
      setCopiedMd(true);
      setTimeout(() => setCopiedMd(false), 2000);
    });
  };

  const handleCopyBadge = () => {
    const badge = `[![TrustScore](https://img.shields.io/badge/TrustScore-${overallScore}%2F100-10b981)](${window.location.origin}/?report=@${username})`;
    navigator.clipboard.writeText(badge).then(() => {
      setCopiedBadge(true);
      setTimeout(() => setCopiedBadge(false), 2000);
    });
  };

  const handleCopyLink = () => {
    const link = `${window.location.origin}${window.location.pathname}?report=${reportId}`;
    navigator.clipboard.writeText(link).then(() => {
      setCopiedLink(true);
      setTimeout(() => setCopiedLink(false), 2000);
    });
  };

  return (
    <div style={{ marginTop: '20px' }}>
      {/* 24-Hour Cache Notification Banner */}
      {cached && (
        <div style={{
          background: 'var(--info-dim)',
          border: '1px solid rgba(59, 130, 246, 0.25)',
          borderRadius: 'var(--radius-md)',
          padding: '12px 18px',
          marginBottom: '20px',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          flexWrap: 'wrap',
          gap: '10px'
        }}>
          <span style={{ fontSize: '0.88rem', color: 'var(--info-text)', fontWeight: 600 }}>
            ⚡ Served from 24h cache (analyzed {new Date(cachedAt).toLocaleTimeString()})
          </span>
          <button
            onClick={onRefresh}
            disabled={isRefreshing}
            style={{
              padding: '6px 12px',
              borderRadius: 'var(--radius-sm)',
              background: 'var(--surface)',
              border: '1px solid var(--border)',
              fontSize: '0.8rem',
              fontWeight: 600,
              cursor: isRefreshing ? 'not-allowed' : 'pointer',
              display: 'inline-flex',
              alignItems: 'center',
              gap: '6px'
            }}
          >
            <RefreshCw size={13} className={isRefreshing ? 'spinner' : ''} />
            <span>{isRefreshing ? 'Re-analyzing…' : 'Re-analyze Live ↻'}</span>
          </button>
        </div>
      )}

      {/* Report Header Card */}
      <div style={{
        background: 'var(--surface)',
        border: '1px solid var(--border)',
        borderRadius: 'var(--radius-lg)',
        padding: '28px',
        boxShadow: 'var(--shadow-md)',
        marginBottom: '20px'
      }}>
        <div style={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'flex-start',
          gap: '20px',
          flexWrap: 'wrap'
        }}>
          <div>
            <h2 style={{
              fontSize: '1.8rem',
              fontWeight: 800,
              letterSpacing: '-0.02em',
              marginBottom: '6px'
            }}>
              @{username}
            </h2>
            <div style={{
              display: 'flex',
              gap: '16px',
              color: 'var(--text-muted)',
              fontSize: '0.88rem',
              flexWrap: 'wrap'
            }}>
              <span>📦 <strong>{rawAnalysis.totalNonForkRepos}</strong> Public Repos</span>
              <span>🚀 <strong>{sp.repoCount}</strong> Standalone</span>
              <span>📋 <strong>{ar.repoCount}</strong> Coursework</span>
              <span>📅 Joined <strong>{new Date(rawAnalysis.profileCreatedAt).getFullYear()}</strong></span>
            </div>
          </div>

          <ScoreRing score={overallScore} />
        </div>

        {/* Toolbar */}
        <div style={{
          display: 'flex',
          gap: '8px',
          marginTop: '20px',
          paddingTop: '18px',
          borderTop: '1px solid var(--border)',
          flexWrap: 'wrap',
          alignItems: 'center'
        }}>
          <button
            onClick={handleCopyMarkdown}
            style={{
              padding: '7px 14px',
              borderRadius: 'var(--radius-sm)',
              background: 'var(--surface-raised)',
              border: '1px solid var(--border)',
              color: 'var(--text-main)',
              fontSize: '0.82rem',
              fontWeight: 600,
              cursor: 'pointer',
              display: 'inline-flex',
              alignItems: 'center',
              gap: '6px'
            }}
          >
            {copiedMd ? <Check size={14} color="#10b981" /> : <Copy size={14} />}
            <span>{copiedMd ? 'Copied Markdown!' : 'Copy Markdown'}</span>
          </button>

          <button
            onClick={handleCopyBadge}
            style={{
              padding: '7px 14px',
              borderRadius: 'var(--radius-sm)',
              background: 'var(--surface-raised)',
              border: '1px solid var(--border)',
              color: 'var(--text-main)',
              fontSize: '0.82rem',
              fontWeight: 600,
              cursor: 'pointer',
              display: 'inline-flex',
              alignItems: 'center',
              gap: '6px'
            }}
          >
            {copiedBadge ? <Check size={14} color="#10b981" /> : <Share2 size={14} />}
            <span>{copiedBadge ? 'Badge Copied!' : 'Copy Badge'}</span>
          </button>

          <button
            onClick={() => window.print()}
            style={{
              padding: '7px 14px',
              borderRadius: 'var(--radius-sm)',
              background: 'var(--surface-raised)',
              border: '1px solid var(--border)',
              color: 'var(--text-main)',
              fontSize: '0.82rem',
              fontWeight: 600,
              cursor: 'pointer',
              display: 'inline-flex',
              alignItems: 'center',
              gap: '6px'
            }}
          >
            <Printer size={14} />
            <span>Print Report</span>
          </button>

          {reportId && (
            <div style={{ display: 'flex', gap: '6px', flex: 1, minWidth: '220px', marginLeft: 'auto' }}>
              <input
                type="text"
                readOnly
                value={`${window.location.origin}${window.location.pathname}?report=${reportId}`}
                style={{
                  flex: 1,
                  padding: '6px 10px',
                  borderRadius: 'var(--radius-sm)',
                  border: '1px solid var(--border)',
                  background: 'var(--bg)',
                  fontSize: '0.78rem',
                  fontFamily: 'var(--font-mono)',
                  color: 'var(--text-muted)'
                }}
              />
              <button
                onClick={handleCopyLink}
                style={{
                  padding: '6px 12px',
                  borderRadius: 'var(--radius-sm)',
                  background: 'var(--surface-raised)',
                  border: '1px solid var(--border)',
                  color: 'var(--text-main)',
                  fontSize: '0.8rem',
                  fontWeight: 600,
                  cursor: 'pointer'
                }}
              >
                {copiedLink ? 'Copied!' : 'Copy'}
              </button>
            </div>
          )}
        </div>
      </div>

      {/* 2-Column Overview Cards */}
      <div style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))',
        gap: '16px',
        marginBottom: '20px'
      }}>
        <div style={{
          background: 'var(--surface)',
          border: '1px solid var(--border)',
          borderRadius: 'var(--radius-lg)',
          padding: '22px',
          boxShadow: 'var(--shadow-sm)'
        }}>
          <h3 style={{ fontSize: '1.05rem', fontWeight: 700, marginBottom: '10px' }}>
            🚀 Standalone Projects Analysis
          </h3>
          <p style={{ color: 'var(--text-muted)', fontSize: '0.92rem', lineHeight: 1.6 }}>
            {aiReport.standalone_summary || 'No standalone project repositories found to evaluate.'}
          </p>
        </div>

        <div style={{
          background: 'var(--surface)',
          border: '1px solid var(--border)',
          borderRadius: 'var(--radius-lg)',
          padding: '22px',
          boxShadow: 'var(--shadow-sm)'
        }}>
          <h3 style={{ fontSize: '1.05rem', fontWeight: 700, marginBottom: '10px' }}>
            📋 Coursework & Assignments
          </h3>
          <p style={{ color: 'var(--text-muted)', fontSize: '0.92rem', lineHeight: 1.6 }}>
            {aiReport.assignment_summary || 'No coursework repositories identified.'}
          </p>
          <span style={{ display: 'block', marginTop: '8px', fontSize: '0.78rem', color: 'var(--info-text)' }}>
            ℹ️ Coursework repositories typically follow single-push patterns, which is normal and not penalized.
          </span>
        </div>

        <div style={{
          background: 'var(--surface)',
          border: '1px solid var(--border)',
          borderRadius: 'var(--radius-lg)',
          padding: '22px',
          boxShadow: 'var(--shadow-sm)'
        }}>
          <h3 style={{ fontSize: '1.05rem', fontWeight: 700, marginBottom: '12px', display: 'flex', alignItems: 'center', gap: '6px' }}>
            <CheckCircle2 size={18} color="#10b981" />
            <span>Verified Positive Signals</span>
          </h3>
          <ul style={{ listStyle: 'none', display: 'flex', flexDirection: 'column', gap: '8px' }}>
            {(aiReport.positive_signals || []).map((s, i) => (
              <li key={i} style={{ fontSize: '0.9rem', color: 'var(--text-main)', display: 'flex', alignItems: 'flex-start', gap: '8px' }}>
                <span style={{ color: '#10b981', fontWeight: 700 }}>✓</span>
                <span>{s}</span>
              </li>
            ))}
          </ul>
        </div>

        <div style={{
          background: 'var(--surface)',
          border: '1px solid var(--border)',
          borderRadius: 'var(--radius-lg)',
          padding: '22px',
          boxShadow: 'var(--shadow-sm)'
        }}>
          <h3 style={{ fontSize: '1.05rem', fontWeight: 700, marginBottom: '12px', display: 'flex', alignItems: 'center', gap: '6px' }}>
            <AlertTriangle size={18} color="#f59e0b" />
            <span>Discussion Points & Flags</span>
          </h3>
          <ul style={{ listStyle: 'none', display: 'flex', flexDirection: 'column', gap: '8px' }}>
            {(aiReport.worth_reviewing || []).map((s, i) => (
              <li key={i} style={{ fontSize: '0.9rem', color: 'var(--text-main)', display: 'flex', alignItems: 'flex-start', gap: '8px' }}>
                <span style={{ color: '#f59e0b', fontWeight: 700 }}>•</span>
                <span>{s}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* Tailored Interview Questions Component */}
      <InterviewQuestions questions={aiReport.interview_questions} />

      {/* Recommendation Card */}
      <div style={{
        background: 'var(--surface)',
        border: '1px solid var(--border)',
        borderRadius: 'var(--radius-lg)',
        padding: '22px',
        boxShadow: 'var(--shadow-sm)',
        marginBottom: '20px'
      }}>
        <h3 style={{ fontSize: '1.05rem', fontWeight: 700, marginBottom: '8px' }}>
          💡 Assessment Recommendation
        </h3>
        <p style={{ fontSize: '0.95rem', fontWeight: 500, color: 'var(--text-main)' }}>
          {aiReport.recommendation}
        </p>
      </div>

      {/* Interactive Repository Explorer */}
      <RepoExplorer standaloneRepos={sp.repoAnalyses} assignmentRepos={ar.repoAnalyses} />
    </div>
  );
}
